name: Publish docs to head
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all history and tags are fetched

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Check for existing cache
        id: check-cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache/pip
          restore-keys: |
            mkdocs-material-

      - name: Generate Cache Key if missing
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: echo "cache_id=mkdocs-material-$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Install dependencies (if cache is missing)
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
          echo "🔍 Cache not found. Installing dependencies..."
          python -m pip install --upgrade pip
          pip install --disable-pip-version-check -r requirements.txt mike
          mkdir -p ~/.cache/pip

      - name: Check and initialize gh-pages if missing
        id: check_branch
        run: |
          if git ls-remote --heads origin gh-pages | grep -q gh-pages; then
            echo "✅ gh-pages branch already exists. Deploying docs with mike"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "🚀 gh-pages branch is missing. Initialising docs with mkdocs..."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Run init_docs Reusable Workflow if gh-pages is missing
        if: steps.check_branch.outputs.exists == 'false'
        run: mkdocs gh-deploy

      - name: Deploy latest changes from main branch (head)
        run: mike deploy head --push
